baseURL = 'https://lammaocc.hk/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'LOCC'
  metaDescription = "Lamma Outrigger Canoe Club"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[taxonomies]
  category= "theme"
  scene = "scenes"
